### ISSUE TITLE
[BUG] Failed to import transformers.models.fuyu.processing_fuyu

### ISSUE THREAD

**Issue by vyomakesh09** [kyegomez/swarms#94] opened 2023-11-05 01:05 UTC
RuntimeError: Failed to import transformers.models.fuyu.processing_fuyu because of the following error (look up to see its traceback):
typing.Optional requires a single type. Got <module 'PIL.Image' from '/usr/lib/python3/dist-packages/PIL/Image.py'>.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/94">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/94/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/94/pledge.svg">
</picture>
</a>

**Comment by evelynmitchell** [comment] 2023-11-05 21:22
This looks to be a duplicate of #95 .
This can be closed.

**Closed** 2023-11-08 16:54 UTC
Labels: bug
